"""refine document model for requirements items

Revision ID: 12176ade09ea
Revises: 980aada4de8e
Create Date: 2026-04-16 22:54:38.690938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12176ade09ea'
down_revision = '980aada4de8e'
branch_labels = None
depends_on = None


def upgrade():
    from alembic import op
    import sqlalchemy as sa

    # 1. Add column as NULLABLE first
    with op.batch_alter_table('document_template_fields') as batch_op:
        batch_op.add_column(sa.Column('scope', sa.String(length=50), nullable=True))

    # 2. Backfill existing data
    op.execute("""
        UPDATE document_template_fields
        SET scope = 'document'
    """)

    # 3. Set NOT NULL after filling values
    with op.batch_alter_table('document_template_fields') as batch_op:
        batch_op.alter_column('scope', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requirement_document_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('project_documents_requirement_document_id_fkey'), 'requirement_documents', ['requirement_document_id'], ['id'])

    with op.batch_alter_table('document_template_fields', schema=None) as batch_op:
        batch_op.drop_column('scope')

    op.drop_table('project_document_item_values')
    op.drop_table('project_document_items')
    # ### end Alembic commands ###
