"""add user_type to users

Revision ID: 316627160a71
Revises: ed697b09d799
Create Date: 2026-04-14 16:36:09.833962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '316627160a71'
down_revision = 'ed697b09d799'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('user_type')

    # ### end Alembic commands ###
