"""Update requirement change requests table

Revision ID: 3d51f2bbdf0a
Revises: f537f0480c93
Create Date: 2026-05-06 13:52:07.497902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d51f2bbdf0a'
down_revision = 'f537f0480c93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requirement_change_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('review_due_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('review_decisions_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('decided_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requirement_change_requests', schema=None) as batch_op:
        batch_op.drop_column('decided_at')
        batch_op.drop_column('review_decisions_json')
        batch_op.drop_column('review_due_at')
        batch_op.drop_column('review_days')

    # ### end Alembic commands ###
