"""Add requirement change requests

Revision ID: 3fa7b108ddf4
Revises: 89aaf32c39c6
Create Date: 2026-05-03 19:42:25.175254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fa7b108ddf4'
down_revision = '89aaf32c39c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requirement_change_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('requested_by_name', sa.String(length=255), nullable=False),
    sa.Column('requested_date', sa.Date(), nullable=True),
    sa.Column('change_type', sa.String(length=80), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('intended_change', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('current_requirement_snapshot', sa.Text(), nullable=True),
    sa.Column('stakeholder_form_filename', sa.String(length=255), nullable=True),
    sa.Column('stakeholder_form_path', sa.String(length=500), nullable=True),
    sa.Column('stakeholder_form_mime_type', sa.String(length=120), nullable=True),
    sa.Column('stakeholder_form_size', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('submitted_by', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['project_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['requirement_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requirement_change_requests')
    # ### end Alembic commands ###
