"""change the structure of organization, organization_member, role, user_roles, and users table

Revision ID: 55f0d9a3b799
Revises: 57e3a43720dc
Create Date: 2026-03-16 14:49:12.057017

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '55f0d9a3b799'
down_revision = '57e3a43720dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization_members', schema=None) as batch_op:
        batch_op.drop_column('joined_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('joined_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
