"""add project stakeholders and project id to user roles

Revision ID: 6ca421400aae
Revises: d3ef44ac5462
Create Date: 2026-04-25 18:17:12.041805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ca421400aae'
down_revision = 'd3ef44ac5462'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_stakeholders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('added_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id', name='uq_project_stakeholder')
    )
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_user_role'), type_='unique')
        batch_op.create_unique_constraint('uq_user_project_role', ['user_id', 'project_id', 'role_id'])
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_user_project_role', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_user_role'), ['user_id', 'role_id'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('project_id')

    op.drop_table('project_stakeholders')
    # ### end Alembic commands ###
