"""add requirement_documents and link requirements

Revision ID: 980aada4de8e
Revises: ed697b09d799
Create Date: 2026-04-16 19:31:54.182122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '980aada4de8e'
down_revision = 'ed697b09d799'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requirement_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['document_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requirement_document_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'requirement_documents', ['requirement_document_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_documents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('requirement_document_id')

    op.drop_table('requirement_documents')
    # ### end Alembic commands ###
