"""Update update requirement change request

Revision ID: d383d877ebcc
Revises: 3d51f2bbdf0a
Create Date: 2026-05-06 15:30:58.072766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd383d877ebcc'
down_revision = '3d51f2bbdf0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requirement_change_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('impact_analysis_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('impact_analysis_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('impact_analysis_mime_type', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('impact_analysis_size', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('impact_analysis_uploaded_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('impact_analysis_uploaded_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('impact_analysis_notes', sa.Text(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['impact_analysis_uploaded_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requirement_change_requests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('impact_analysis_notes')
        batch_op.drop_column('impact_analysis_uploaded_at')
        batch_op.drop_column('impact_analysis_uploaded_by')
        batch_op.drop_column('impact_analysis_size')
        batch_op.drop_column('impact_analysis_mime_type')
        batch_op.drop_column('impact_analysis_path')
        batch_op.drop_column('impact_analysis_filename')

    # ### end Alembic commands ###
