"""add requirement item value

Revision ID: d3ef44ac5462
Revises: 5f76725e0195
Create Date: 2026-04-17 03:50:38.387315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3ef44ac5462'
down_revision = '5f76725e0195'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requirement_item_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('template_field_id', sa.Integer(), nullable=False),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['requirement_items.id'], ),
    sa.ForeignKeyConstraint(['template_field_id'], ['document_template_fields.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_template_fields', schema=None) as batch_op:
        batch_op.drop_column('scope')

    with op.batch_alter_table('requirement_items', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('requirement_code')
        batch_op.drop_column('priority')
        batch_op.drop_column('description')
        batch_op.drop_column('title')
        batch_op.drop_column('rationale')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requirement_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rationale', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('priority', sa.VARCHAR(length=50), server_default=sa.text("'Medium'::character varying"), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('requirement_code', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'Draft'::character varying"), autoincrement=False, nullable=False))

    with op.batch_alter_table('document_template_fields', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scope', sa.VARCHAR(length=50), autoincrement=False, nullable=False))

    op.drop_table('requirement_item_values')
    # ### end Alembic commands ###
