"""Add project_id foreign key to user_roles table

Revision ID: e731e9329e8b
Revises: d3ef44ac5462
Create Date: 2026-04-20 14:51:34.118667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e731e9329e8b'
down_revision = 'd3ef44ac5462'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_user_role'), type_='unique')
        batch_op.create_unique_constraint('uq_user_role_project', ['user_id', 'role_id', 'project_id'])
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('user_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('user_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_user_role_project', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_user_role'), ['user_id', 'role_id'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('project_id')

    # ### end Alembic commands ###
