"""Add change request log

Revision ID: f537f0480c93
Revises: 3fa7b108ddf4
Create Date: 2026-05-05 11:46:59.423159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f537f0480c93'
down_revision = '3fa7b108ddf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requirement_change_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('before_snapshot', sa.Text(), nullable=True),
    sa.Column('after_snapshot', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['project_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['requirement_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('requirement_approvals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('review_requested_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('review_due_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('requested_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('auto_approved_at', sa.DateTime(), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_requirement_approval_document_user'), type_='unique')
        batch_op.create_unique_constraint('uq_requirement_approval_item_user', ['item_id', 'user_id'])
        batch_op.create_foreign_key(None, 'users', ['requested_by'], ['id'])
        batch_op.create_foreign_key(None, 'requirement_items', ['item_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requirement_approvals', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_requirement_approval_item_user', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_requirement_approval_document_user'), ['document_id', 'user_id'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('auto_approved_at')
        batch_op.drop_column('requested_by')
        batch_op.drop_column('review_due_at')
        batch_op.drop_column('review_requested_at')
        batch_op.drop_column('item_id')

    op.drop_table('requirement_change_logs')
    # ### end Alembic commands ###
