"""add user_roles and organization_members tables

Revision ID: ff76858938db
Revises: 7f5bad2f02af
Create Date: 2026-03-16 14:29:46.179353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff76858938db'
down_revision = '7f5bad2f02af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('users_organization_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('users_role_id_fkey'), type_='foreignkey')
        batch_op.drop_column('role_id')
        batch_op.drop_column('organization_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('users_role_id_fkey'), 'roles', ['role_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('users_organization_id_fkey'), 'organizations', ['organization_id'], ['id'])

    # ### end Alembic commands ###
